import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-master-secret",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
};

// ---- File input validation (path confinement, size and type limits) ----
const MAX_FILE_BYTES = 1_000_000;
const MAX_TOTAL_BYTES = 20_000_000;
const MAX_FILES = 500;
const FILE_CONTENT_TYPES: Record<string, string> = {
  html: "text/html", htm: "text/html", css: "text/css", js: "text/javascript", mjs: "text/javascript",
  jsx: "text/plain", ts: "text/plain", tsx: "text/plain", json: "application/json", md: "text/markdown",
  txt: "text/plain", svg: "image/svg+xml", xml: "application/xml", yml: "text/plain", yaml: "text/plain",
  toml: "text/plain", sql: "text/plain", py: "text/plain", sh: "text/plain", env: "text/plain",
  gitignore: "text/plain", lock: "text/plain", vue: "text/plain", svelte: "text/plain", java: "text/plain",
  kt: "text/plain", gradle: "text/plain", properties: "text/plain", csv: "text/csv",
};
function validateFiles(files: unknown): { ok: true; files: { path: string; content: string; contentType: string }[] } | { ok: false; error: string } {
  if (!Array.isArray(files)) return { ok: false, error: "files must be an array" };
  if (files.length > MAX_FILES) return { ok: false, error: `Too many files (max ${MAX_FILES})` };
  const out: { path: string; content: string; contentType: string }[] = [];
  let total = 0;
  for (const f of files as any[]) {
    const path = typeof f?.path === "string" ? f.path.trim() : "";
    if (!path || path.length > 300 || path.startsWith("/") || path.includes("\\") || path.includes("\0") ||
        path.split("/").some((seg: string) => seg === "" || seg === "." || seg === "..") ||
        !/^[A-Za-z0-9._\-\/@ ]+$/.test(path)) {
      return { ok: false, error: `Invalid file path: ${String(f?.path ?? "").slice(0, 100)}` };
    }
    if (typeof f?.content !== "string") return { ok: false, error: `File content must be text: ${path}` };
    const size = new TextEncoder().encode(f.content).length;
    if (size > MAX_FILE_BYTES) return { ok: false, error: `File too large (max 1 MB): ${path}` };
    total += size;
    if (total > MAX_TOTAL_BYTES) return { ok: false, error: "Total file size too large (max 20 MB)" };
    const base = path.split("/").pop() || "";
    const ext = (base.includes(".") ? base.split(".").pop() : base.replace(/^\./, ""))!.toLowerCase();
    const contentType = FILE_CONTENT_TYPES[ext];
    if (!contentType) return { ok: false, error: `File type not allowed: ${path}` };
    out.push({ path, content: f.content, contentType });
  }
  return { ok: true, files: out };
}

function jsonResponse(data: any, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function checkSupabaseConnection() {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) {
    throw new Error("CONNECTION_ERROR: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing.");
  }
  return createClient(url, key);
}

function sanitizeProjectName(raw: string): string {
  const cleaned = (raw || "").replace(/[^a-zA-Z0-9 _.-]/g, "").trim().slice(0, 64);
  return cleaned || "tivo-project";
}

// Build a downloadable ZIP-like JSON bundle with installer scripts
function buildDownloadBundle(project: any, files: any[]) {
  const projectName = sanitizeProjectName(project.name);
  const safeDescription = (project.description || "").replace(/[<>`$]/g, "").slice(0, 500);

  // Generate README
  const readme = `# ${projectName}

${safeDescription || "Generated by TIVO AI OS Software Factory"}

## Quick Start

### Windows
Double-click \`install.bat\`

### macOS / Linux
\`\`\`bash
chmod +x setup.sh
./setup.sh
\`\`\`

## Manual Setup
\`\`\`bash
npm install
npm run dev
\`\`\`

---
Built with TIVO AI OS • ${new Date().toISOString()}
`;

  // Ensure README exists
  const hasReadme = files.some((f: any) => f.path.toLowerCase().includes("readme"));
  const allFiles = hasReadme ? files : [{ path: "README.md", content: readme }, ...files];

  return {
    project_name: projectName,
    description: project.description,
    files: allFiles,
    metadata: {
      generated_at: new Date().toISOString(),
      file_count: allFiles.length,
      total_size: allFiles.reduce((s: number, f: any) => s + (f.content?.length || 0), 0),
      build_status: project.build_status,
      audit_score: project.build_metadata?.audit_score || null,
      version_count: project.version_history?.length || 0,
    },
    instructions: {
      windows: "Double-click install.bat to setup and run",
      unix: "Run: chmod +x setup.sh && ./setup.sh",
      manual: "Run: npm install && npm run dev",
    },
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // === Multi-tenant resolver ===
    const providedSecret = req.headers.get("x-master-secret");
    function resolveTenant(s: string | null): string | null {
      if (!s) return null;
      if (s === Deno.env.get("MASTER_SECRET")) return "tenant_main";
      for (let i = 2; i <= 50; i++) {
        const v = Deno.env.get(`MASTER_SECRET_${i}`);
        if (v && s === v) return `tenant_${i}`;
      }
      if (s === Deno.env.get("SUPER_ADMIN_MASTER_SECRET")) return "super_admin";
      return null;
    }

    // Verify a Supabase user JWT server-side (never trust client-supplied identity).
    // Accepted either via `Authorization: Bearer <jwt>` or as the x-master-secret value
    // when that value is a JWT (session-token mode — keeps raw secrets out of browsers).
    const LOCKED_SUPER_ADMIN_EMAIL = "pureproducts61@gmail.com";
    const looksLikeJwt = (v: string | null) => !!v && v.split(".").length === 3 && v.length > 60;
    async function verifyUserJwt(token: string | null): Promise<{ id: string; email: string } | null> {
      if (!looksLikeJwt(token)) return null;
      const supaUrl = Deno.env.get("SUPABASE_URL");
      const supaAnon = Deno.env.get("SUPABASE_ANON_KEY") || Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
      if (!supaUrl || !supaAnon) return null;
      try {
        const c = createClient(supaUrl, supaAnon);
        const { data, error } = await c.auth.getUser(token!);
        if (error || !data?.user) return null;
        return { id: data.user.id, email: (data.user.email || "").trim().toLowerCase() };
      } catch { return null; }
    }

    const bearer = (req.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim() || null;
    // A verified user identity gives us user-level authorization on top of tenant isolation.
    const verifiedUser =
      (await verifyUserJwt(bearer)) ??
      (looksLikeJwt(providedSecret) ? await verifyUserJwt(providedSecret) : null);

    let tenantId = resolveTenant(providedSecret);
    // Session-token mode: super admin authenticates with their verified Supabase JWT,
    // so the raw master secret never has to reach the browser.
    if (!tenantId && verifiedUser?.email === LOCKED_SUPER_ADMIN_EMAIL) tenantId = "super_admin";
    if (!tenantId) return jsonResponse({ error: "Unauthorized" }, 401);
    const isSuperAdmin = tenantId === "super_admin";

    // Optional hard requirement: every non-super-admin caller must present a verified user JWT.
    if (!isSuperAdmin && Deno.env.get("REQUIRE_USER_JWT") === "true" && !verifiedUser) {
      return jsonResponse({ error: "Unauthorized — verified user session required" }, 401);
    }

    let supabase: any;
    try {
      supabase = checkSupabaseConnection();
    } catch (connErr) {
      console.error("[connection_error]", connErr);
      return jsonResponse({ error: "Database not available", alert: "ADMIN_CONNECTION_ERROR" }, 503);
    }

    // Helper: scope query to current tenant unless super admin.
    // When the caller proved a user identity, also scope to that user (user-level authorization).
    const scope = (q: any) => {
      if (isSuperAdmin) return q;
      let out = q.eq("tenant_id", tenantId);
      if (verifiedUser) out = out.eq("user_id", verifiedUser.id);
      return out;
    };

    // Ownership guard used before any privileged (service-role) side effect on a project.
    async function assertOwnedProject(projectId: string): Promise<boolean> {
      if (!projectId) return false;
      const { data } = await scope(supabase.from("projects").select("id").eq("id", projectId)).maybeSingle();
      return !!data;
    }

    const url = new URL(req.url);
    const pathParts = url.pathname.split("/").filter(Boolean);
    const action = pathParts[pathParts.length - 1] || "";

    // === LIST PROJECTS ===
    if (action === "list" && req.method === "GET") {
      const user_id = url.searchParams.get("user_id");
      const status = url.searchParams.get("status");
      let query = supabase.from("projects").select("id, name, description, status, build_status, public_url, installer_url, created_at, updated_at, build_metadata, version_history, tenant_id").order("updated_at", { ascending: false });
      query = scope(query);
      if (user_id && (isSuperAdmin || !verifiedUser)) query = query.eq("user_id", user_id);
      if (status) query = query.eq("status", status);

      const { data, error } = await query;
      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);
      return jsonResponse({ projects: data, tenant_id: tenantId });
    }

    // === GET PROJECT ===
    if (action === "get" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data, error } = await scope(supabase.from("projects").select("*").eq("id", id)).maybeSingle();
      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);
      if (!data) return jsonResponse({ error: "Not found or access denied" }, 404);
      return jsonResponse({ project: data });
    }

    // === GET VERSION HISTORY ===
    if (action === "versions" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data, error } = await scope(supabase.from("projects").select("version_history, build_metadata").eq("id", id)).maybeSingle();
      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);
      if (!data) return jsonResponse({ error: "Not found or access denied" }, 404);
      return jsonResponse({ versions: data?.version_history || [], metadata: data?.build_metadata || {} });
    }

    const body = req.method !== "GET" ? await req.json().catch(() => ({})) : {};

    // === CREATE PROJECT ===
    if (action === "create" && req.method === "POST") {
      const { user_id, name, description, repo_url, files } = body;
      const cleanName = sanitizeProjectName(name || "");
      if (!cleanName || cleanName.length < 1) return jsonResponse({ error: "valid name required (1-64 chars, alnum/space/._-)" }, 400);

      // Ownership can never come from client input: use the verified session identity.
      // Only a super admin may create a project on behalf of another user_id.
      const ownerUserId = verifiedUser
        ? verifiedUser.id
        : isSuperAdmin
          ? (typeof user_id === "string" && user_id ? user_id : "system")
          : null;
      if (!ownerUserId) return jsonResponse({ error: "Unauthorized — verified user session required to create a project" }, 401);
      const vf = validateFiles(files || []);
      if (!vf.ok) return jsonResponse({ error: vf.error }, 400);
      const cleanFiles = vf.files.map(({ path, content }) => ({ path, content }));

      const { data, error } = await supabase.from("projects").insert({
        user_id: ownerUserId,
        tenant_id: tenantId,
        name: cleanName,
        description: (description || "").toString().slice(0, 2000),
        repo_url: repo_url || "",
        files: cleanFiles,
        status: "active",
        build_status: "pending",
        version_history: [{ version: 1, timestamp: new Date().toISOString(), note: "Initial creation" }],
      }).select().single();

      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);

      // Upload initial files
      if (vf.files.length && data?.id) {
        for (const file of vf.files) {
          await supabase.storage.from("project-files").upload(
            `${data.id}/${file.path}`,
            new TextEncoder().encode(file.content),
            { contentType: file.contentType, upsert: true }
          );
        }
      }

      const { data: signed } = await supabase.storage.from("project-files").createSignedUrl(`${data.id}/index.html`, 60 * 60 * 24 * 365);
      const publicUrl = signed?.signedUrl || null;
      await supabase.from("projects").update({ public_url: publicUrl }).eq("id", data.id);
      return jsonResponse({ success: true, project: { ...data, public_url: publicUrl } });
    }

    // === UPDATE PROJECT ===
    if (action === "update" && req.method === "PUT") {
      const { id } = body;
      if (!id) return jsonResponse({ error: "id required" }, 400);
      // Only an explicit allowlist of fields may be changed by callers.
      const updates: Record<string, any> = {};
      if (body.name !== undefined) {
        const n = sanitizeProjectName(String(body.name || ""));
        if (!n) return jsonResponse({ error: "valid name required" }, 400);
        updates.name = n;
      }
      if (body.description !== undefined) updates.description = String(body.description ?? "").slice(0, 2000);
      if (body.repo_url !== undefined) {
        const r = String(body.repo_url ?? "");
        if (r && !/^https:\/\/[^\s]{1,500}$/.test(r)) return jsonResponse({ error: "repo_url must be https" }, 400);
        updates.repo_url = r;
      }
      if (body.build_status !== undefined) {
        const allowed = ["pending", "queued", "building", "success", "failed", "audited", "tested_clean", "tested_fixed", "files_uploaded", "idle", "live", "paused", "stopped", "published"];
        if (!allowed.includes(String(body.build_status))) return jsonResponse({ error: "invalid build_status" }, 400);
        updates.build_status = String(body.build_status);
      }
      if (body.status !== undefined) {
        if (!["active", "archived", "live", "paused", "stopped", "idle"].includes(String(body.status))) return jsonResponse({ error: "invalid status" }, 400);
        updates.status = String(body.status);
      }
      let validatedFiles: { path: string; content: string; contentType: string }[] | null = null;
      if (body.files !== undefined) {
        const vf = validateFiles(body.files);
        if (!vf.ok) return jsonResponse({ error: vf.error }, 400);
        validatedFiles = vf.files;
        updates.files = vf.files.map(({ path, content }) => ({ path, content }));
      }
      if (!Object.keys(updates).length) return jsonResponse({ error: "no updatable fields supplied" }, 400);

      // Verify ownership BEFORE any storage write (prevents cross-tenant overwrite/defacement)
      const { data: owned } = await scope(supabase.from("projects").select("id, version_history, files").eq("id", id)).maybeSingle();
      if (!owned) return jsonResponse({ error: "Project not found" }, 404);

      // Save version before update if files changed
      if (validatedFiles) {
        const history = (owned.version_history as any[]) || [];
        history.push({
          version: history.length + 1,
          timestamp: new Date().toISOString(),
          note: "Updated via API",
          file_count: updates.files.length,
        });
        updates.version_history = history.slice(-50);

        // Re-upload files to storage
        for (const file of validatedFiles) {
          await supabase.storage.from("project-files").upload(
            `${id}/${file.path}`,
            new TextEncoder().encode(file.content),
            { contentType: file.contentType, upsert: true }
          );
        }
      }

      const { error } = await scope(supabase.from("projects").update(updates).eq("id", id));
      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);
      return jsonResponse({ success: true });
    }

    // === DELETE PROJECT ===
    if (action === "delete" && req.method === "DELETE") {
      const { id } = body;
      if (!id) return jsonResponse({ error: "id required" }, 400);

      // Verify ownership BEFORE storage cleanup (prevents cross-tenant file deletion)
      const { data: owned } = await scope(supabase.from("projects").select("id").eq("id", id)).maybeSingle();
      if (!owned) return jsonResponse({ error: "Project not found" }, 404);

      // Recursively delete storage files
      async function deleteFolder(prefix: string) {
        const { data: items } = await supabase.storage.from("project-files").list(prefix, { limit: 1000 });
        if (items?.length) {
          const filePaths = items.filter((i: any) => i.id).map((f: any) => `${prefix}/${f.name}`);
          const folders = items.filter((i: any) => !i.id);
          if (filePaths.length) await supabase.storage.from("project-files").remove(filePaths);
          for (const folder of folders) await deleteFolder(`${prefix}/${folder.name}`);
        }
      }
      await deleteFolder(id);

      const { error } = await scope(supabase.from("projects").delete().eq("id", id));
      if (error) return jsonResponse((console.error("[db_error]", error), { error: "Database operation failed" }), 500);
      return jsonResponse({ success: true });
    }

    // === UPLOAD FILES ===
    if (action === "upload-files" && req.method === "POST") {
      const { project_id, files } = body;
      if (!project_id || !files?.length) return jsonResponse({ error: "project_id and files required" }, 400);

      // Verify ownership BEFORE any storage write (prevents cross-tenant prefix pollution)
      const { data: owned, error: ownErr } = await scope(
        supabase.from("projects").select("id").eq("id", project_id)
      ).maybeSingle();
      if (ownErr) { console.error("[db_error]", ownErr); return jsonResponse({ error: "Database operation failed" }, 500); }
      if (!owned) return jsonResponse({ error: "Project not found or access denied" }, 404);


      const vf = validateFiles(files);
      if (!vf.ok) return jsonResponse({ error: vf.error }, 400);
      const results = [];
      for (const file of vf.files) {
        const storagePath = `${project_id}/${file.path}`;
        const content = new TextEncoder().encode(file.content);
        const { error } = await supabase.storage.from("project-files").upload(storagePath, content, {
          contentType: file.contentType,
          upsert: true,
        });
        const { data: signed } = error ? { data: null } : await supabase.storage.from("project-files").createSignedUrl(storagePath, 60 * 60 * 24 * 365);
        results.push({
          path: file.path,
          success: !error,
          url: signed?.signedUrl || null,
        });
      }

      // Update project files metadata + version
      const { data: project } = await scope(supabase.from("projects").select("files, version_history").eq("id", project_id)).single();
      const existingFiles = (project?.files as any[]) || [];
      const newFiles = [...existingFiles];
      for (const r of results) {
        if (!r.success) continue;
        const idx = newFiles.findIndex((f: any) => f.path === r.path);
        const entry = { path: r.path, url: r.url, updated_at: new Date().toISOString() };
        if (idx >= 0) newFiles[idx] = entry; else newFiles.push(entry);
      }

      const history = (project?.version_history as any[]) || [];
      history.push({ version: history.length + 1, timestamp: new Date().toISOString(), note: `Uploaded ${files.length} files` });

      await scope(supabase.from("projects").update({
        files: newFiles,
        build_status: "files_uploaded",
        version_history: history.slice(-50),
      }).eq("id", project_id));

      return jsonResponse({ success: true, uploads: results });
    }

    // === PUBLISH PROJECT ===
    if (action === "publish" && req.method === "POST") {
      const { project_id } = body;
      if (!project_id) return jsonResponse({ error: "project_id required" }, 400);
      // Ownership check BEFORE creating any signed URL (service-role client bypasses RLS).
      if (!(await assertOwnedProject(project_id))) {
        return jsonResponse({ error: "Project not found" }, 404);
      }
      // Short-lived signed URL instead of a 1-year link.
      const { data: signed } = await supabase.storage.from("project-files").createSignedUrl(`${project_id}/index.html`, 60 * 60);
      const publicUrl = signed?.signedUrl || null;
      const installerUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/project-manager/download?id=${project_id}&format=zip`;
      await scope(supabase.from("projects").update({
        status: "published",
        build_status: "live",
        public_url: publicUrl,
        installer_url: installerUrl,
      }).eq("id", project_id));
      return jsonResponse({ success: true, public_url: publicUrl, installer_url: installerUrl });
    }


    // === DOWNLOAD PROJECT (Ready-to-Run Bundle) ===
    if (action === "download" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);

      const { data: project } = await scope(supabase.from("projects").select("*").eq("id", id)).single();
      if (!project) return jsonResponse({ error: "Project not found" }, 404);

      // Get files from storage
      const { data: storageFiles } = await supabase.storage.from("project-files").list(id, { limit: 1000 });
      const downloadFiles = [];

      if (storageFiles?.length) {
        for (const sf of storageFiles) {
          if (!sf.id) continue; // skip folders
          const { data: fileData } = await supabase.storage.from("project-files").download(`${id}/${sf.name}`);
          if (fileData) {
            const text = await fileData.text();
            downloadFiles.push({ path: sf.name, content: text, size: text.length });
          }
        }
      }

      const files = downloadFiles.length ? downloadFiles : (project.files as any[]) || [];
      const bundle = buildDownloadBundle(project, files);

      // Log download
      await supabase.from("memory_logs").insert({
        action: "project_downloaded",
        tenant_id: tenantId,
        details: { project_id: id, project_name: project.name, file_count: files.length, tenant_id: tenantId },
      });

      return jsonResponse({ success: true, bundle });
    }

    // === GET PUBLIC URL ===
    if (action === "public-url" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data } = await scope(supabase.from("projects").select("public_url, installer_url, status, build_status, build_metadata").eq("id", id)).single();
      if (!data) return jsonResponse({ error: "Project not found" }, 404);
      return jsonResponse(data);
    }

    return jsonResponse({ error: `Unknown project action: ${action}` }, 404);
  } catch (e) {
    console.error("Project Manager error:", e);
    return jsonResponse({ error: "Internal server error" }, 500);
  }
});
