import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-master-secret",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
};

function jsonResponse(data: any, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function checkSupabaseConnection() {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !key) {
    throw new Error("CONNECTION_ERROR: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing.");
  }
  return createClient(url, key);
}

// Build a downloadable ZIP-like JSON bundle with installer scripts
function buildDownloadBundle(project: any, files: any[]) {
  const projectName = project.name || "tivo-project";

  // Generate README
  const readme = `# ${projectName}

${project.description || "Generated by TIVO AI OS Software Factory"}

## Quick Start

### Windows
Double-click \`install.bat\`

### macOS / Linux
\`\`\`bash
chmod +x setup.sh
./setup.sh
\`\`\`

## Manual Setup
\`\`\`bash
npm install
npm run dev
\`\`\`

---
Built with TIVO AI OS • ${new Date().toISOString()}
`;

  // Ensure README exists
  const hasReadme = files.some((f: any) => f.path.toLowerCase().includes("readme"));
  const allFiles = hasReadme ? files : [{ path: "README.md", content: readme }, ...files];

  return {
    project_name: projectName,
    description: project.description,
    files: allFiles,
    metadata: {
      generated_at: new Date().toISOString(),
      file_count: allFiles.length,
      total_size: allFiles.reduce((s: number, f: any) => s + (f.content?.length || 0), 0),
      build_status: project.build_status,
      audit_score: project.build_metadata?.audit_score || null,
      version_count: project.version_history?.length || 0,
    },
    instructions: {
      windows: "Double-click install.bat to setup and run",
      unix: "Run: chmod +x setup.sh && ./setup.sh",
      manual: "Run: npm install && npm run dev",
    },
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // === Multi-tenant resolver ===
    const providedSecret = req.headers.get("x-master-secret");
    function resolveTenant(s: string | null): string | null {
      if (!s) return null;
      if (s === Deno.env.get("MASTER_SECRET")) return "tenant_main";
      for (let i = 2; i <= 50; i++) {
        const v = Deno.env.get(`MASTER_SECRET_${i}`);
        if (v && s === v) return `tenant_${i}`;
      }
      if (s === Deno.env.get("SUPER_ADMIN_MASTER_SECRET")) return "super_admin";
      return null;
    }
    const tenantId = resolveTenant(providedSecret);
    if (!tenantId) return jsonResponse({ error: "Unauthorized" }, 401);
    const isSuperAdmin = tenantId === "super_admin";

    let supabase: any;
    try {
      supabase = checkSupabaseConnection();
    } catch (connErr) {
      return jsonResponse({ error: connErr instanceof Error ? connErr.message : "Connection Error", alert: "ADMIN_CONNECTION_ERROR" }, 503);
    }

    // Helper: scope query to current tenant unless super admin
    const scope = (q: any) => isSuperAdmin ? q : q.eq("tenant_id", tenantId);

    const url = new URL(req.url);
    const pathParts = url.pathname.split("/").filter(Boolean);
    const action = pathParts[pathParts.length - 1] || "";

    // === LIST PROJECTS ===
    if (action === "list" && req.method === "GET") {
      const user_id = url.searchParams.get("user_id");
      const status = url.searchParams.get("status");
      let query = supabase.from("projects").select("id, name, description, status, build_status, public_url, installer_url, created_at, updated_at, build_metadata, version_history, tenant_id").order("updated_at", { ascending: false });
      query = scope(query);
      if (user_id) query = query.eq("user_id", user_id);
      if (status) query = query.eq("status", status);
      const { data, error } = await query;
      if (error) return jsonResponse({ error: error.message }, 500);
      return jsonResponse({ projects: data, tenant_id: tenantId });
    }

    // === GET PROJECT ===
    if (action === "get" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data, error } = await scope(supabase.from("projects").select("*").eq("id", id)).maybeSingle();
      if (error) return jsonResponse({ error: error.message }, 500);
      if (!data) return jsonResponse({ error: "Not found or access denied" }, 404);
      return jsonResponse({ project: data });
    }

    // === GET VERSION HISTORY ===
    if (action === "versions" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data, error } = await scope(supabase.from("projects").select("version_history, build_metadata").eq("id", id)).maybeSingle();
      if (error) return jsonResponse({ error: error.message }, 500);
      if (!data) return jsonResponse({ error: "Not found or access denied" }, 404);
      return jsonResponse({ versions: data?.version_history || [], metadata: data?.build_metadata || {} });
    }

    const body = req.method !== "GET" ? await req.json().catch(() => ({})) : {};

    // === CREATE PROJECT ===
    if (action === "create" && req.method === "POST") {
      const { user_id, name, description, repo_url, files } = body;
      if (!name) return jsonResponse({ error: "name required" }, 400);

      const { data, error } = await supabase.from("projects").insert({
        user_id: user_id || "system",
        tenant_id: tenantId,
        name,
        description: description || "",
        repo_url: repo_url || "",
        files: files || [],
        status: "active",
        build_status: "pending",
        version_history: [{ version: 1, timestamp: new Date().toISOString(), note: "Initial creation" }],
      }).select().single();

      if (error) return jsonResponse({ error: error.message }, 500);

      // Upload initial files
      if (files?.length && data?.id) {
        const contentTypes: Record<string, string> = {
          html: "text/html", css: "text/css", js: "application/javascript",
          json: "application/json", ts: "application/javascript", tsx: "application/javascript",
        };
        for (const file of files) {
          const ext = file.path.split(".").pop() || "txt";
          await supabase.storage.from("project-files").upload(
            `${data.id}/${file.path}`,
            new TextEncoder().encode(file.content),
            { contentType: contentTypes[ext] || "text/plain", upsert: true }
          );
        }
      }

      const publicUrl = `${Deno.env.get("SUPABASE_URL")}/storage/v1/object/public/project-files/${data.id}/index.html`;
      await supabase.from("projects").update({ public_url: publicUrl }).eq("id", data.id);
      return jsonResponse({ success: true, project: { ...data, public_url: publicUrl } });
    }

    // === UPDATE PROJECT ===
    if (action === "update" && req.method === "PUT") {
      const { id, ...updates } = body;
      if (!id) return jsonResponse({ error: "id required" }, 400);

      // Save version before update if files changed
      if (updates.files) {
        const { data: current } = await supabase.from("projects").select("version_history, files").eq("id", id).single();
        const history = (current?.version_history as any[]) || [];
        history.push({
          version: history.length + 1,
          timestamp: new Date().toISOString(),
          note: "Updated via API",
          file_count: updates.files.length,
        });
        updates.version_history = history.slice(-50);

        // Re-upload files to storage
        const contentTypes: Record<string, string> = {
          html: "text/html", css: "text/css", js: "application/javascript",
          json: "application/json", ts: "application/javascript", tsx: "application/javascript",
        };
        for (const file of updates.files) {
          const ext = file.path.split(".").pop() || "txt";
          await supabase.storage.from("project-files").upload(
            `${id}/${file.path}`,
            new TextEncoder().encode(file.content),
            { contentType: contentTypes[ext] || "text/plain", upsert: true }
          );
        }
      }

      const { error } = await supabase.from("projects").update(updates).eq("id", id);
      if (error) return jsonResponse({ error: error.message }, 500);
      return jsonResponse({ success: true });
    }

    // === DELETE PROJECT ===
    if (action === "delete" && req.method === "DELETE") {
      const { id } = body;
      if (!id) return jsonResponse({ error: "id required" }, 400);

      // Recursively delete storage files
      async function deleteFolder(prefix: string) {
        const { data: items } = await supabase.storage.from("project-files").list(prefix, { limit: 1000 });
        if (items?.length) {
          const filePaths = items.filter((i: any) => i.id).map((f: any) => `${prefix}/${f.name}`);
          const folders = items.filter((i: any) => !i.id);
          if (filePaths.length) await supabase.storage.from("project-files").remove(filePaths);
          for (const folder of folders) await deleteFolder(`${prefix}/${folder.name}`);
        }
      }
      await deleteFolder(id);

      const { error } = await supabase.from("projects").delete().eq("id", id);
      if (error) return jsonResponse({ error: error.message }, 500);
      return jsonResponse({ success: true });
    }

    // === UPLOAD FILES ===
    if (action === "upload-files" && req.method === "POST") {
      const { project_id, files } = body;
      if (!project_id || !files?.length) return jsonResponse({ error: "project_id and files required" }, 400);

      const results = [];
      for (const file of files) {
        const storagePath = `${project_id}/${file.path}`;
        const content = new TextEncoder().encode(file.content);
        const { error } = await supabase.storage.from("project-files").upload(storagePath, content, {
          contentType: file.content_type || "text/plain",
          upsert: true,
        });
        results.push({
          path: file.path,
          success: !error,
          url: `${Deno.env.get("SUPABASE_URL")}/storage/v1/object/public/project-files/${storagePath}`,
        });
      }

      // Update project files metadata + version
      const { data: project } = await supabase.from("projects").select("files, version_history").eq("id", project_id).single();
      const existingFiles = (project?.files as any[]) || [];
      const newFiles = [...existingFiles];
      for (const r of results) {
        if (!r.success) continue;
        const idx = newFiles.findIndex((f: any) => f.path === r.path);
        const entry = { path: r.path, url: r.url, updated_at: new Date().toISOString() };
        if (idx >= 0) newFiles[idx] = entry; else newFiles.push(entry);
      }

      const history = (project?.version_history as any[]) || [];
      history.push({ version: history.length + 1, timestamp: new Date().toISOString(), note: `Uploaded ${files.length} files` });

      await supabase.from("projects").update({
        files: newFiles,
        build_status: "files_uploaded",
        version_history: history.slice(-50),
      }).eq("id", project_id);

      return jsonResponse({ success: true, uploads: results });
    }

    // === PUBLISH PROJECT ===
    if (action === "publish" && req.method === "POST") {
      const { project_id } = body;
      if (!project_id) return jsonResponse({ error: "project_id required" }, 400);
      const publicUrl = `${Deno.env.get("SUPABASE_URL")}/storage/v1/object/public/project-files/${project_id}/index.html`;
      const installerUrl = `${Deno.env.get("SUPABASE_URL")}/functions/v1/project-manager/download?id=${project_id}&format=zip`;
      await supabase.from("projects").update({
        status: "published",
        build_status: "live",
        public_url: publicUrl,
        installer_url: installerUrl,
      }).eq("id", project_id);
      return jsonResponse({ success: true, public_url: publicUrl, installer_url: installerUrl });
    }

    // === DOWNLOAD PROJECT (Ready-to-Run Bundle) ===
    if (action === "download" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);

      const { data: project } = await supabase.from("projects").select("*").eq("id", id).single();
      if (!project) return jsonResponse({ error: "Project not found" }, 404);

      // Get files from storage
      const { data: storageFiles } = await supabase.storage.from("project-files").list(id, { limit: 1000 });
      const downloadFiles = [];

      if (storageFiles?.length) {
        for (const sf of storageFiles) {
          if (!sf.id) continue; // skip folders
          const { data: fileData } = await supabase.storage.from("project-files").download(`${id}/${sf.name}`);
          if (fileData) {
            const text = await fileData.text();
            downloadFiles.push({ path: sf.name, content: text, size: text.length });
          }
        }
      }

      const files = downloadFiles.length ? downloadFiles : (project.files as any[]) || [];
      const bundle = buildDownloadBundle(project, files);

      // Log download
      await supabase.from("memory_logs").insert({
        action: "project_downloaded",
        details: { project_id: id, project_name: project.name, file_count: files.length },
      });

      return jsonResponse({ success: true, bundle });
    }

    // === GET PUBLIC URL ===
    if (action === "public-url" && req.method === "GET") {
      const id = url.searchParams.get("id");
      if (!id) return jsonResponse({ error: "id required" }, 400);
      const { data } = await supabase.from("projects").select("public_url, installer_url, status, build_status, build_metadata").eq("id", id).single();
      if (!data) return jsonResponse({ error: "Project not found" }, 404);
      return jsonResponse(data);
    }

    return jsonResponse({ error: `Unknown project action: ${action}` }, 404);
  } catch (e) {
    console.error("Project Manager error:", e);
    return jsonResponse({ error: e instanceof Error ? e.message : "Unknown error" }, 500);
  }
});
